# name
name: Python-GUI-and-data-acquisition

# description
description: This repo will contain all the files necessary to run the GUI and data acquisition software needed for the LabJack hardware.

# site theme
theme: jekyll-theme-minimal

# author
author: Graham Scheib
author_email: graham.scheib@und.edu

show_downloads: true
